version: 2.1

jobs:
  build:
    parameters:
      image:
        description: "Name of the docker image (e.g. circleci/ruby:2.5"
        type: string
      command:
        description: "The command to execute (e.g. bundle exec rspec)"
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: bundle lock --update
      - restore_cache:
          keys:
            - v1-<< parameters.image >>-gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/cache
      - save_cache:
          paths:
            - vendor/cache
          key: v1-<< parameters.image >>-gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: << parameters.command >>

workflows:
  build:
    jobs:
      - build:
          image: circleci/ruby:2.3
          command: bundle exec rspec spec
      - build:
          image: circleci/ruby:2.4
          command: bundle exec rspec spec
      - build:
          image: circleci/ruby:2.5
          command: bundle exec rspec spec
      - build:
          image: circleci/ruby:2.5
          command: bundle exec rubocop
